export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const PREFERENCES="PREFERENCES";
export const REGISTRATION_RESPONSE="REGISTRATION_RESPONSE";
export const QUESTIONAIRE="QUESTIONAIRE";
export const REMOVE_QUESTION="REMOVE_QUESTION";
export const UPDATE_PROGRESS="UPDATE_PROGRESS";
export const CHANGE_COUNT="CHANGE_COUNT";